FROM node:22

WORKDIR /app

ENV GITHUB_REPO=IvanLogvynenko/JBTestTask
ENV YOUTRACK_SERVERNAME=ivanlogvynenko
ENV YOUTRACK_PROJECT_ID=
ENV YOUTRACK_PROJECT_NAME=JB

COPY part1.js /app/main.js

COPY package.json package.json

RUN npm install

CMD ["node", "main.js"]


